### ISSUE TITLE
Разработать UseCase

### ISSUE THREAD

**Issue by dalteri** [dalteri/music-site#13]
### [Юз-кейсы для незарегистрированного пользователя](https://github.com/dalteri/music-site/blob/master/Documents/ucUnregistered.png):

![Юз-кейсы для незарегистрированного пользователя](https://github.com/dalteri/music-site/blob/master/Documents/ucUnregistered.png?raw=true)

### [Юз-кейсы исполнителя](https://github.com/dalteri/music-site/blob/master/Documents/ucArtist.png):

![Юз-кейсы исполнителя](https://github.com/dalteri/music-site/blob/master/Documents/ucArtist.png?raw=true)

### [Юз-кейсы композиции](https://github.com/dalteri/music-site/blob/master/Documents/ucMusic.png):

![Юз-кейсы композиции](https://github.com/dalteri/music-site/blob/master/Documents/ucMusic.png?raw=true)

### [Юз-кейсы плейлиста](https://github.com/dalteri/music-site/blob/master/Documents/ucPlaylist.png):

![Юз-кейсы плейлиста](https://github.com/dalteri/music-site/blob/master/Documents/ucPlaylist.png?raw=true)

### [Юз-кейсы страницы пользователя](https://github.com/dalteri/music-site/blob/master/Documents/ucUserPage.png):

![Юз-кейсы страницы пользователя](https://github.com/dalteri/music-site/blob/master/Documents/ucUserPage.png?raw=true)

### [Юз-кейсы поиска](https://github.com/dalteri/music-site/blob/master/Documents/ucSearch.png):

![Юз-кейсы поиска](https://github.com/dalteri/music-site/blob/master/Documents/ucSearch.png?raw=true)

**Comment by wldmr-key** [comment]
да, все хорошо. Единственное - непонятно откуда берутся метки "универсального назначения" и кем они присваиваются. Авторами статей?
Модераторами становятся пожизненно?
поиск по тегам, пользователям, словам в комментариях не предусмотрен?
слушать музыку - это не экстент музыкальной страницы? или просмотра плейлиста (которого нет)

**Comment by wldmr-key** [comment]
И что у нас зависло? нормально все. Пора закрывать задачу и двигать дальше!
