### ISSUE TITLE
Концептуальная схема данных

### ISSUE THREAD

**Issue by dalteri** [dalteri/music-site#2]
Текущая [КонцептуальнаяСхема](https://github.com/dalteri/music-site/blob/master/КонцептуальнаяСхема.png)
![Текущая концептуальная схема](https://github.com/dalteri/music-site/blob/master/КонцептуальнаяСхема.png?raw=true)

[Старая концептуальная схема](https://github.com/dalteri/music-site/blob/master/КонцептуальнаяСхемаСтарая.jpg)

**Comment by wldmr-key** [comment]
**замечание по организации данных** - относится ко всему проекту. Предыдущие версии тоже стоит включать в проект. В частности, мне пришлось искать предыдущий вариант - он мне хоть и не понравился, но часть информации из него потерялась в актуальном

**Comment by wldmr-key** [comment]
по текущей схеме
1) потерялась кратность и модальность связей
2) наименования связей имеет смысл писать, только если они имеют поясняющее значение
3) комментарий может относится к комментарию, так? где связь?
4) возможно, возьму свои слова обратно 

> Нормальный человек скажет: плейлист состоит из композиций. Композиция входит (может и не входить) в плейлисты
> А что у тебя? Плейлист состоит из компонентов плейлиста...
Комментарии, ведь, пишутся к конкретному элементу плейлиста "Вася включил в плейлист Любимое песню Катюша"? - тогда ты прав, я не прав
Или наоборот - все комментарии приклеиваются к песне Катюша? Тогда я по-прежнему прав.
5) что такое пользовательская метка понятно. Что такое метка по-прежнему непонятно. Какова оптимальная политика их возникновения?

**Comment by dalteri** [comment]
@wldmr-key 
> Предыдущие версии тоже стоит включать в проект
Добавил первую версию схемы отдельным файлом. Старые версии текущей, по идее, теперь можно доставать из истории. Если так неудобно — напишите. Буду добавлять новыми файлами, пока не утвердим окончательно.

> 1. потерялась кратность и модальность связей
Добавил

> 2\. наименования связей имеет смысл писать, только если они имеют поясняющее значение
Оставил пояснения на "пользователь - комментарий", остальные убрал.

> 3\. комментарий может относится к комментарию, так? где связь?
Потерялась. Вернул.

> 4\. возможно, возьму свои слова обратно
> 
> > Нормальный человек скажет: плейлист состоит из композиций. Композиция входит (может и не входить) в плейлисты
> > А что у тебя? Плейлист состоит из компонентов плейлиста...
> > Комментарии, ведь, пишутся к конкретному элементу плейлиста "Вася включил в плейлист Любимое песню Катюша"? - тогда ты прав, я не прав
> > Или наоборот - все комментарии приклеиваются к песне Катюша? Тогда я по-прежнему прав.
Комментарии в этом случае относятся либо к плейлисту в целом, либо к конкретным композициям. Элементов тут не должно быть, вы правы.

> 5\. что такое пользовательская метка понятно. Что такое метка по-прежнему непонятно. Какова оптимальная политика их возникновения?
Можно сказать, что:
Метки = объективные качества
Пользовательские метки = субъективные качества
Первые модерируются и отражают конкретный факт, например: жанр, количество вокалистов, наличие какого-то музыкального инструмента.
Вторые — свободно прикрепляются любыми пользователями и могут содержать любые высказывания: "скучно", "эпично", "БЕСТ ОФ ЗЕ БЕСТ", "продам гараж" и т.п.
Просто "метка" либо есть, либо нет. А одна и та же "пользовательская метка" может быть прикреплена к одной(му) песне/исполнителю неограниченное количество раз (но одним конкретным пользователем, к одной конкретной композиции, одна конкретная метка может быть оставлена только один раз).
